In [29]:
import numpy as np
import tensorflow as tf
from imutils import paths



ModuleNotFoundError: No module named 'imutils'

In [22]:
# Vector 1-rank tensors
vector = np.array([6,2,3,1,5,1])
vector_tf = tf.constant([6,2,3,1,5,1])
print(vector.shape)
vector

(6,)


array([6, 2, 3, 1, 5, 1])

In [23]:
# Matrix 2-rank tensors
matrix=np.array([(6,2),(3,1),(5,1)])
print(matrix.shape)
print(matrix)
print(matrix[1][0])

(3, 2)
[[6 2]
 [3 1]
 [5 1]]
3


In [24]:
# Cube 3-rank tensors
cube=np.array([((6,2),(3,1),(5,1)),((6,2),(3,1),(5,1)),((6,2),(3,1),(5,1))])
print(cube.shape)
print(cube[1][0])
cube

(3, 3, 2)
[6 2]


array([[[6, 2],
        [3, 1],
        [5, 1]],

       [[6, 2],
        [3, 1],
        [5, 1]],

       [[6, 2],
        [3, 1],
        [5, 1]]])

In [25]:
F = np.array([[2,-1],[3,0],[-5,2]])
G = np.array([[4,4,-3],[0,-1,-2]])
H = np.array([[1,6],[-1,-2],[0,-3]])

In [28]:
H+F


array([[ 3,  5],
       [ 2, -2],
       [-5, -1]])